"""initial db layout

Revision ID: b0590545d152
Revises: 
Create Date: 2018-02-27 17:40:13.084848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0590545d152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('ipv4', sa.String(length=15), nullable=True),
    sa.Column('ipv6', sa.String(length=45), nullable=True),
    sa.Column('alias', sa.String(length=256), nullable=True),
    sa.Column('vendor', sa.String(length=256), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_first_seen'), 'host', ['first_seen'], unique=False)
    op.create_index(op.f('ix_host_last_seen'), 'host', ['last_seen'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_host_last_seen'), table_name='host')
    op.drop_index(op.f('ix_host_first_seen'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
